DATASET_PATH = 'data'
CORPORA_EXTENSION = '.md'
QUESTIONS_EXTENSION = '.csv'
QUESTIONS_FILENAME = 'questions_df'

CHUNK_SIZE = 200
CHUNK_OVERLAP = 0
MINIMALIZE_CHUNKS = False

EMBD_BATCH_SIZE = 32

OPENAI_API_KEY = None

RERANKER_MULTIPLIER = 3
MAX_WORKERS = 5
